import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Privacy Policy — MaujiTV',
  description:
    'Learn how MaujiTV collects, uses and protects your personal information.',
};

export default function PrivacyPage() {
  return (
    <>
      <div className="page-intro">
        <span className="eyebrow">
          <span className="dot"></span> Legal
        </span>
        <h1 className="page-title">Privacy Policy</h1>
        <p className="page-updated">Last updated: June 22, 2026</p>
      </div>

      <div className="legal-grid">
        <nav className="toc">
          <h5>On this page</h5>
          <ol>
            <li>
              <a href="#overview">Overview</a>
            </li>
            <li>
              <a href="#collect">Information We Collect</a>
            </li>
            <li>
              <a href="#use">How We Use Your Information</a>
            </li>
            <li>
              <a href="#cookies">Cookies &amp; Tracking Technologies</a>
            </li>
            <li>
              <a href="#share">How We Share Information</a>
            </li>
            <li>
              <a href="#retention">Data Retention</a>
            </li>
            <li>
              <a href="#rights">Your Rights &amp; Choices</a>
            </li>
            <li>
              <a href="#children">Children&apos;s Privacy</a>
            </li>
            <li>
              <a href="#security">Data Security</a>
            </li>
            <li>
              <a href="#transfers">International Data Transfers</a>
            </li>
            <li>
              <a href="#changes">Changes to This Policy</a>
            </li>
            <li>
              <a href="#contact">Contact Us</a>
            </li>
          </ol>
        </nav>

        <article className="content-card">
          <section id="overview">
            <h2>
              <span className="num">01</span> Information We Collect
            </h2>
            <p>
              We collect information you provide directly (name, email or phone,
              date of birth, profile details) and information generated by using
              the app (watch history, device and login activity).
            </p>
          </section>

          <section id="collect">
            <h2>
              <span className="num">02</span> How We Use Your Information
            </h2>
            <p>
              We collect information in a few different ways: We use this
              information to operate your account and profiles, process
              subscription payments, personalize recommendations, and improve
              the service.
            </p>
          </section>

          <section id="use">
            <h2>
              <span className="num">03</span> Sharing of Information
            </h2>
            <p>
              We use your information to: We share the minimum information
              necessary with payment processors (such as Razorpay or Easebuzz)
              to complete transactions. We do not sell your personal
              information.
            </p>
          </section>

          <section id="cookies">
            <h2>
              <span className="num">04</span> Data Security
            </h2>
            <p>
              We use industry-standard measures, including encrypted storage of
              credentials, to protect your information. No system is perfectly
              secure, and we encourage you to keep your login details private.
              <a href="/cookie-policy">Cookie Policy</a>.
            </p>
          </section>

          <section id="share">
            <h2>
              <span className="num">05</span> Your Choices
            </h2>
            <p>
              You can update your profile details at any time from Edit Profile,
              and review or sign out of active sessions from Security &
              Sessions. To request access to or deletion of your data, contact
              support@dharvix.com.
            </p>
          </section>

          <section id="retention">
            <h2>
              <span className="num">06</span> Children’s Privacy
            </h2>
            <p>
              Kids profiles are intended to be managed by a parent or guardian
              through the primary account and are restricted to age-appropriate
              content.
            </p>
          </section>

          <section id="rights">
            <h2>
              <span className="num">07</span> Changes to This Policy
            </h2>
            <p>
              We may update this policy as the service evolves. Continued use of
              the app after an update means you accept the revised policy.
            </p>
            <p>
              You can also manage many preferences — such as notification
              settings and connected devices — directly within your account
              settings.
            </p>
          </section>

          <section id="children">
            <h2>
              <span className="num">08</span> Contact
            </h2>
            <p>For any privacy questions, reach us at support@dharvix.com.</p>
          </section>

          <section id="security">
            <h2>
              <span className="num">09</span> Data Security
            </h2>
            <p>
              We use technical and organisational safeguards — including
              encryption in transit, access controls and regular security
              reviews — designed to protect your information. No method of
              transmission or storage is 100% secure, but we work to keep your
              data safe and to respond quickly if something goes wrong.
            </p>
          </section>

          <section id="transfers">
            <h2>
              <span className="num">10</span> International Data Transfers
            </h2>
            <p>
              We may process and store information in countries other than your
              own. Where we transfer personal data internationally, we use
              appropriate safeguards (such as standard contractual clauses) as
              required by applicable law.
            </p>
          </section>

          <section id="changes">
            <h2>
              <span className="num">11</span> Changes to This Policy
            </h2>
            <p>
              We may update this Privacy Policy from time to time. We&apos;ll
              post the revised version here with a new &quot;Last updated&quot;
              date, and for material changes, we&apos;ll provide additional
              notice through the app or by email.
            </p>
          </section>

          <section id="contact">
            <h2>
              <span className="num">12</span> Contact Us
            </h2>
            <p>
              Questions about this Policy or your data? Email our privacy team
              at <a href="mailto:support@dharvix.com">support@dharvix.com</a> or
              visit <a href="/contact">Contact Us</a>.
            </p>
          </section>
        </article>
      </div>
    </>
  );
}
